version: '3.8'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: '
        local.eorzearm.com -> http://apache-php-eorzearm:80,
        local-frontend.eorzearm.com -> http://apache-php-eorzearm:80'
      STAGE: 'local'
      # STAGE: 'staging'
    volumes:
      - ./https-portal-data:/var/lib/https-portal
    networks:
      - staging-network
  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    networks:
      - staging-network
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ALLOW_EMPTY_PASSWORD='no'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
  apache-php-eorzearm:
    build: './apache-php-eorzearm/'
    container_name: apache-php-eorzearm
    volumes:
      - ./apache-php-eorzearm/www:/var/www/html
      - ./apache-php-eorzearm/apache/virtualhosts:/etc/apache2/sites-enabled/
      - ./apache-php-eorzearm/apache/sites-available/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./https-portal-data:/etc/apache2/certs/
    networks:
      - staging-network
    command: 
      - apache2-foreground
networks:
  staging-network:
    attachable: true